# Default values for castle.pshq.org.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
homeassistant:
  replicaCount: 1
  labels:
     app: homeassistant
  image:
    repository: homeassistant/home-assistant
    tag: stable
  service:
    type: ClusterIP
    port: 8123
    externalIPs: 192.168.0.121
    targetPort: 8123
  pvc:
    size: 10Gi

mariadb:
  replicaCount: 1
  image:
    repository: mariadb
    tag: latest
  auth:
    rootPassword:
      secretKeyRef:
        name: mariadb-password
        key: password
    database: "homeassistant"
    username: "homeassistant"
    password:
      secretKeyRef:
        name: dbuserpw
        key: password  
  service:
    type: ClusterIP
    port: 3306
  user: homeassistant
  database: homeassistant
  pvc:
    size: 10Gi
phpmyadmin:
  db:
    host: mariadb
  service:
    type: LoadBalancer
    externalIPs:
      - 192.168.0.121
  ingress:
    enabled: false
