apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_USER
          value: homeassistant
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: password
        - name: MYSQL_DATABASE
          value: homeassistant
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
