apiVersion: v1
kind: Service
metadata:
  name: HomeAssistantService
  labels:
    {{ .Values.homeassistant.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs: {{ .Values.homeassistant.service.externalIPs }}
  ports:
    - port: {{ .Values.homeassistant.service.port }}
      targetPort: {{ .Values.homeassistant.service.targetPort }}
      protocol: TCP
      name: http